### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Nunya-9018** [TheRemote/MinecraftBedrockServer#58] opened 2020-12-29 15:02 UTC
is there away to change the info in the consle to time stamps
![image](https://user-images.githubusercontent.com/73594766/103292988-f8190280-49bc-11eb-90ff-d360691492cc.png)

**Comment by HockeyGuy10** [comment] 2021-01-18 16:22
I would love this as well, but it's something the bedrock server developers will have to fix.  I don't think there's anything we can do .

**Comment by murkyl** [comment] 2021-04-27 02:11
Look at issue #71 which is essentially a duplicate of this one. I also added a comment with how to do this without an external script.

**Comment by TheRemote** [comment] 2021-06-20 00:51
This has been fixed!

**Closed by TheRemote** 2021-06-20 00:51 UTC
