### ISSUE TITLE
Starting server deletes all start/stop/restart files

### ISSUE THREAD

**Issue by troop61killbuck** [TheRemote/MinecraftBedrockServer#54] opened 2020-12-16 14:26 UTC
I downloaded today (12/16/2020) and whenever the server starts it deletes the following files (to my knowledge): 
- bedrock_server
- libCrypto.so
- server.properties
- stop.sh
- restart.sh
- start.sh
- valid_known_packs.json

**Comment by 10xOXR** [comment] 2020-12-16 18:20
Having the same issue! The server starts successfully on first installation, however running "start.sh" or "restart.sh" cuases the above behaviour. Console shows:

`Sending restart notifications to server...
Closing server...
Backing up server (to minecraftbe/Bearserver/backups folder)
worlds/
worlds/Bedrock level/
worlds/Bedrock level/db/
worlds/Bedrock level/db/000003.log
worlds/Bedrock level/db/CURRENT
worlds/Bedrock level/db/MANIFEST-000002
worlds/Bedrock level/levelname.txt
worlds/Bedrock level/level.dat
worlds/Bedrock level/level.dat_old
rm: cannot remove 'structures': Is a directory
rm: cannot remove 'resource_packs': Is a directory
rm: cannot remove 'definitions': Is a directory
rm: cannot remove 'behavior_packs': Is a directory
rm: cannot remove 'downloads': Is a directory
rm: cannot remove 'logs': Is a directory
rm: cannot remove 'world_templates': Is a directory
Checking for the latest version of Minecraft Bedrock server ...
--2020-12-16 18:12:19--  https://minecraft.net/en-us/download/server/bedrock/
Resolving minecraft.net (minecraft.net)... 99.86.123.42, 99.86.123.48, 99.86.123.41, ...
Connecting to minecraft.net (minecraft.net)|99.86.123.42|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.minecraft.net/en-us/download/server/bedrock/ [following]
--2020-12-16 18:12:19--  https://www.minecraft.net/en-us/download/server/bedrock/
Resolving www.minecraft.net (www.minecraft.net)... 72.247.177.34, 72.247.177.42
Connecting to www.minecraft.net (www.minecraft.net)|72.247.177.34|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.minecraft.net/en-us/download/server/bedrock [following]
--2020-12-16 18:12:20--  https://www.minecraft.net/en-us/download/server/bedrock
Reusing existing connection to www.minecraft.net:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘downloads/version.html’

downloads/version.html                     [ <=>                                                                         ] 302.88K  --.-KB/s    in 0.08s

2020-12-16 18:12:20 (3.54 MB/s) - ‘downloads/version.html’ saved [310145]

Minecraft Bedrock server is up to date...
Starting Minecraft server.  To view window type screen -r Bearserver
To minimize the window and let the server run in the background, press Ctrl+A then Ctrl+D`

The files noted in the OP are then gone from the minecraftbe folder and I have to reinstall., but to the same issue. 

Something else of note is that when the server starts for the first time it appears as _"Dedicated Server"_ in Minecraft rather than the server name that was chosen during installation.

**Comment by 10xOXR** [comment] 2020-12-16 18:48
Update: Reverting to the previous version of "start.sh" by removing `ls -1tr | head -n -10 | xargs -d '\n' rm -f --` resolves the issue.

**Comment by welbo97** [comment] 2020-12-17 17:14
Confirmed issue here as well. Using 'SetupMinecraft.sh' created the proper running server. After stopping it with a Ctrl-C inside screen the using ./start.sh, files are removed from the server directory. Looks like the update process is failing to find files to download. Maybe a sanity test to make sure it gets new files before running the rm -rf in the script?

Here's my output from running ./start.sh:

```
wuser@bedrock:~/minecraftbe/userock$ ll
total 358900
drwxrwxr-x 17 wuser wuser        26 Dec 17 11:00 ./
drwxrwxr-x 14 wuser wuser        15 Dec 17 10:58 ../
-rw-r--r--  1 wuser wuser         0 Dec 17 10:59 Dedicated_Server.txt
drwxrwxr-x  2 wuser wuser         2 Dec 17 10:58 backups/
-rwxr-xr-x  1 wuser wuser 366639608 Dec 11 19:15 bedrock_server*
drwxr-xr-x 14 wuser wuser        14 Dec 11 18:38 behavior_packs/
drwxr-xr-x  9 wuser wuser         9 Dec 11 18:38 definitions/
drwxr-xr-x  2 wuser wuser         2 Dec 17 10:59 development_behavior_packs/
drwxr-xr-x  2 wuser wuser         2 Dec 17 10:59 development_resource_packs/
drwxr-xr-x  2 wuser wuser         2 Dec 17 10:59 development_skin_packs/
drwxrwxr-x  2 wuser wuser         4 Dec 17 10:58 downloads/
-rwxr-xr-x  1 wuser wuser    878304 Dec 11 18:38 libCrypto.so*
drwxrwxr-x  2 wuser wuser         3 Dec 17 10:59 logs/
drwxr-xr-x  2 wuser wuser         2 Dec 17 10:59 minecraftpe/
-rw-rw-r--  1 wuser wuser       416 Dec 17 11:00 ops.json
drwxr-xr-x  2 wuser wuser         2 Dec 17 10:59 premium_cache/
drwxr-xr-x  4 wuser wuser         4 Dec 11 18:38 resource_packs/
-rwxrwxr-x  1 wuser wuser      1720 Dec 17 10:59 restart.sh*
-rw-r--r--  1 wuser wuser      3686 Dec 17 10:59 server.properties
-rwxrwxr-x  1 wuser wuser      2835 Dec 17 10:58 start.sh*
-rwxrwxr-x  1 wuser wuser      1917 Dec 17 10:59 stop.sh*
drwxr-xr-x 14 wuser wuser        14 Dec 11 18:38 structures/
drwxr-xr-x  3 wuser wuser         3 Dec 17 10:59 treatments/
-rw-r--r--  1 wuser wuser      2656 Dec 17 10:59 valid_known_packs.json
drwxr-xr-x  2 wuser wuser         2 Dec 17 10:59 world_templates/
drwxr-xr-x  3 wuser wuser         3 Dec 17 10:59 worlds/
wuser@bedrock:~/minecraftbe/userock$ ./st
start.sh    stop.sh     structures/ 
wuser@bedrock:~/minecraftbe/userock$ cp ../bedrock_server/whitelist.json .
wuser@bedrock:~/minecraftbe/userock$ cat whitelist.json 
[]

wuser@bedrock:~/minecraftbe/userock$ ./start.sh 
Backing up server (to minecraftbe/userock/backups folder)
worlds/
worlds/Bedrock level/
worlds/Bedrock level/level.dat
worlds/Bedrock level/db/
worlds/Bedrock level/db/000003.log
worlds/Bedrock level/db/MANIFEST-000002
worlds/Bedrock level/db/CURRENT
worlds/Bedrock level/levelname.txt
rm: cannot remove 'structures': Is a directory
rm: cannot remove 'resource_packs': Is a directory
rm: cannot remove 'definitions': Is a directory
rm: cannot remove 'behavior_packs': Is a directory
rm: cannot remove 'downloads': Is a directory
rm: cannot remove 'logs': Is a directory
rm: cannot remove 'world_templates': Is a directory
Checking for the latest version of Minecraft Bedrock server ...
--2020-12-17 11:01:31--  https://minecraft.net/en-us/download/server/bedrock/
Resolving minecraft.net (minecraft.net)... 65.8.218.44, 65.8.218.51, 65.8.218.64, ...
Connecting to minecraft.net (minecraft.net)|65.8.218.44|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.minecraft.net/en-us/download/server/bedrock/ [following]
--2020-12-17 11:01:31--  https://www.minecraft.net/en-us/download/server/bedrock/
Resolving www.minecraft.net (www.minecraft.net)... 23.47.51.61, 23.47.51.52
Connecting to www.minecraft.net (www.minecraft.net)|23.47.51.61|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.minecraft.net/en-us/download/server/bedrock [following]
--2020-12-17 11:01:31--  https://www.minecraft.net/en-us/download/server/bedrock
Reusing existing connection to www.minecraft.net:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'downloads/version.html'

downloads/version.html         [ <=>                                  ] 302.88K  --.-KB/s    in 0.07s   

2020-12-17 11:01:32 (4.03 MB/s) - 'downloads/version.html' saved [310146]

Minecraft Bedrock server is up to date...
Starting Minecraft server.  To view window type screen -r userock
To minimize the window and let the server run in the background, press Ctrl+A then Ctrl+D
wuser@bedrock:~/minecraftbe/userock$ screen -r
There is no screen to be resumed.
wuser@bedrock:~/minecraftbe/userock$ ll
total 88
drwxrwxr-x 17 wuser wuser  19 Dec 17 11:01 ./
drwxrwxr-x 14 wuser wuser  15 Dec 17 10:58 ../
drwxrwxr-x  2 wuser wuser   3 Dec 17 11:01 backups/
drwxr-xr-x 14 wuser wuser  14 Dec 11 18:38 behavior_packs/
drwxr-xr-x  9 wuser wuser   9 Dec 11 18:38 definitions/
drwxr-xr-x  2 wuser wuser   2 Dec 17 10:59 development_behavior_packs/
drwxr-xr-x  2 wuser wuser   2 Dec 17 10:59 development_resource_packs/
drwxr-xr-x  2 wuser wuser   2 Dec 17 10:59 development_skin_packs/
drwxrwxr-x  2 wuser wuser   4 Dec 17 10:58 downloads/
drwxrwxr-x  2 wuser wuser   4 Dec 17 11:01 logs/
drwxr-xr-x  2 wuser wuser   2 Dec 17 10:59 minecraftpe/
-rw-rw-r--  1 wuser wuser 416 Dec 17 11:00 ops.json
drwxr-xr-x  2 wuser wuser   2 Dec 17 10:59 premium_cache/
drwxr-xr-x  4 wuser wuser   4 Dec 11 18:38 resource_packs/
drwxr-xr-x 14 wuser wuser  14 Dec 11 18:38 structures/
drwxr-xr-x  3 wuser wuser   3 Dec 17 10:59 treatments/
-rw-r--r--  1 wuser wuser   3 Dec 17 11:01 whitelist.json
drwxr-xr-x  2 wuser wuser   2 Dec 17 10:59 world_templates/
drwxr-xr-x  3 wuser wuser   3 Dec 17 10:59 worlds/
wuser@bedrock:~/minecraftbe/userock$ 

```

**Comment by lurk24** [comment] 2020-12-19 02:22
i am experiencing the same issue

**Comment by TheRemote** [comment] 2020-12-23 04:30
Hey guys,

Sorry this was fixed.  I had to make a hard path to the logs folder.

**Closed by TheRemote** 2020-12-23 04:30 UTC
